### ISSUE TITLE
Burde bruke faktiske kommuner

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMambassador#2]
Heller enn PL-id

**Comment by AsgeirSH** [comment]
@mariusmandal Hvor bør denne bruke faktiske kommuner?

**Comment by mariusmandal** [comment]
I dag velger man hvilken mønstring de tilhører, vi burde velge kommuner i
stedet. Så alle steder vi beregner tilhørighet (også der vi henter ut alle
fra et fylke / en mønstring)
man. 5. sep. 2016 kl. 18.10 skrev AsgeirSH <notifications@github.com>:

**Comment by mariusmandal** [comment]
@AsgeirSH Denne må vi snakke om i morgen - tror det er en veldig viktig endring å få med akkurat nå :)
